# File extension for shared libraries.
SOLIB_EXT = dylib

# Extra gcc flags.
PLATFORM_CFLAGS = -arch x86_64 -arch i386 -g \
	-I/System/Library/Frameworks/JavaVM.framework/Headers

# Extra flags for linking shared libraries.
LDFLAGS = -arch x86_64 -arch i386 -dynamiclib

JAVA_LDFLAGS = -framework JavaVM

include common.mk
