# Note:  If you are using a Mac with Xcode 4 or later, you will need to
#        set processor architecture flags before running make:
#           ARCHFLAGS="-arch i386 -arch x86_64" 

.PHONY: build install clean

build:
	python setup.py build

install:
	python setup.py install

clean:
	python setup.py clean

