/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_puredata_core_PdBase */

#ifndef _Included_org_puredata_core_PdBase
#define _Included_org_puredata_core_PdBase
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_puredata_core_PdBase
 * Method:    clearSearchPath
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_puredata_core_PdBase_clearSearchPath
  (JNIEnv *, jclass);

/*
 * Class:     org_puredata_core_PdBase
 * Method:    addToSearchPath
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_puredata_core_PdBase_addToSearchPath
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_puredata_core_PdBase
 * Method:    setReceiver
 * Signature: (Lorg/puredata/core/PdReceiver;)V
 */
JNIEXPORT void JNICALL Java_org_puredata_core_PdBase_setReceiver
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_puredata_core_PdBase
 * Method:    openAudio
 * Signature: (IIII)I
 */
JNIEXPORT jint JNICALL Java_org_puredata_core_PdBase_openAudio
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     org_puredata_core_PdBase
 * Method:    processRaw
 * Signature: ([F[F)I
 */
JNIEXPORT jint JNICALL Java_org_puredata_core_PdBase_processRaw
  (JNIEnv *, jclass, jfloatArray, jfloatArray);

/*
 * Class:     org_puredata_core_PdBase
 * Method:    process
 * Signature: ([S[S)I
 */
JNIEXPORT jint JNICALL Java_org_puredata_core_PdBase_process___3S_3S
  (JNIEnv *, jclass, jshortArray, jshortArray);

/*
 * Class:     org_puredata_core_PdBase
 * Method:    process
 * Signature: ([F[F)I
 */
JNIEXPORT jint JNICALL Java_org_puredata_core_PdBase_process___3F_3F
  (JNIEnv *, jclass, jfloatArray, jfloatArray);

/*
 * Class:     org_puredata_core_PdBase
 * Method:    process
 * Signature: ([D[D)I
 */
JNIEXPORT jint JNICALL Java_org_puredata_core_PdBase_process___3D_3D
  (JNIEnv *, jclass, jdoubleArray, jdoubleArray);

/*
 * Class:     org_puredata_core_PdBase
 * Method:    exists
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_puredata_core_PdBase_exists
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_puredata_core_PdBase
 * Method:    sendBang
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_puredata_core_PdBase_sendBang
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_puredata_core_PdBase
 * Method:    sendFloat
 * Signature: (Ljava/lang/String;F)I
 */
JNIEXPORT jint JNICALL Java_org_puredata_core_PdBase_sendFloat
  (JNIEnv *, jclass, jstring, jfloat);

/*
 * Class:     org_puredata_core_PdBase
 * Method:    sendSymbol
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_puredata_core_PdBase_sendSymbol
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     org_puredata_core_PdBase
 * Method:    blockSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_puredata_core_PdBase_blockSize
  (JNIEnv *, jclass);

/*
 * Class:     org_puredata_core_PdBase
 * Method:    initialize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_puredata_core_PdBase_initialize
  (JNIEnv *, jclass);

/*
 * Class:     org_puredata_core_PdBase
 * Method:    startMessage
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_puredata_core_PdBase_startMessage
  (JNIEnv *, jclass);

/*
 * Class:     org_puredata_core_PdBase
 * Method:    addFloat
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_org_puredata_core_PdBase_addFloat
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     org_puredata_core_PdBase
 * Method:    addSymbol
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_puredata_core_PdBase_addSymbol
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_puredata_core_PdBase
 * Method:    finishList
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_puredata_core_PdBase_finishList
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_puredata_core_PdBase
 * Method:    finishMessage
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_puredata_core_PdBase_finishMessage
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     org_puredata_core_PdBase
 * Method:    bindSymbol
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_puredata_core_PdBase_bindSymbol
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_puredata_core_PdBase
 * Method:    unbindSymbol
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_puredata_core_PdBase_unbindSymbol
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
